---
- name: Docker | Set up Docker daemon
  become: yes
  become_method: sudo
  block:
    # sudo apt-get install *
    - name: Install docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gpg-agent

    # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # sudo apt-key fingerprint 0EBFCD88
    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present

    # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker

    # sudo apt-get install docker-ce docker-compose
    - name: Install docker
      apt:
        name: 
          - docker-ce
          - docker-compose
        state: present
        update_cache: yes

    # Start and enable docker on boot
    - name: Docker | Ensure Docker is enabled and started
      service:
        name: docker
        state: started
        enabled: true
      register: docker_first_start

    # Wait for docker response
    - name: Docker | Ensure Docker is up and responsive
      uri:
        unix_socket: /var/run/docker.sock
        url: http://docker/version
        timeout: 2
      register: _result
      until: _result.status == 200
      retries: 15
      delay: 2
      check_mode: no

    # sudo adduser deploy
    - name: Ensure users is created
      user:
        name: "{{ item }}"
        state: present
      loop:
          - "{{ ansible_user }}"
          - deploy
          - docker

    # sudo groupadd docker deploy
    - name: Ensure "docker" and "deploy" groups are created
      group:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - "{{ ansible_user }}"
