# This playbook contains docker actions that will be run on "remote" host.

# sudo apt-get install *
- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker
  become: true
  become_method: sudo

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
  become: true
  become_method: sudo

# sudo apt-key fingerprint 0EBFCD88
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
  become: true
  become_method: sudo

# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker
  become: true
  become_method: sudo

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - docker
  become: true
  become_method: sudo

# sudo apt-get install docker-ce=18.03.*
- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot
  tags:
    - docker
  become: true
  become_method: sudo

# sudo groupadd docker
- name: Ensure "docker" group is created
  group:
    name: docker
    state: present
  tags:
    - docker
  become: true
  become_method: sudo

- name: Get current username
  shell: whoami
  register: username_on_the_host

# sudo usermod -aG docker vagrant
- name: Add "vagrant" user to "docker" group
  user:
    name: "{{ username_on_the_host.stdout }}"
    group: docker
    append: yes
  tags:
    - docker
  become: true
  become_method: sudo

# sudo usermod -aG docker deploy
- name: Add remote "deploy" user to "docker" group
  user:
    name: deploy
    group: docker
    append: yes
  tags:
    - docker
  become: true
  become_method: sudo
  
# # Download docker-compose via curl
# - name: Install docker-compose
#   remote_user: ubuntu
#   get_url: 
#     url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: 'u+x,g+x'

# Install pip3 to install SDK
- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true
  become_method: sudo

# Install Docker SDK
- name: Install docker python package
  pip:
    name: docker

# Install Docker-compose
- name: Install docker-compose python package
  pip:
    name: docker-compose