# This playbook contains common handlers that can be called in "docker-compose" tasks.

# sudo systemctl enable docker
- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true
  become_method: sudo